# Generated by Django 4.2.6 on 2023-10-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filter_db", "0002_remove_student_id_alter_student_student_id_projects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="student_id",
        ),
    ]
